In [1]:
import numpy as np

In [2]:
# Create list of basket boll player named height_cm
height_cm = [180, 215, 210, 210, 188, 176, 209, 200 , 210 , 189 , 210]

In [3]:
# Create a numpy array from height_cm: np_height_cm
np_height_cm = np.array(height_cm)

In [5]:
# Printing type of np_height_cm
print(type(np_height_cm))

<class 'numpy.ndarray'>


In [6]:
# Printing the array
np_height_cm

array([180, 215, 210, 210, 188, 176, 209, 200, 210, 189, 210])

In [7]:
# Turning cm to metre
np_height_m = np_height_cm/100
np_height_m

array([1.8 , 2.15, 2.1 , 2.1 , 1.88, 1.76, 2.09, 2.  , 2.1 , 1.89, 2.1 ])

In [15]:
# Create list weight_pound
weight_pound = [150 , 275 , 169 , 236 , 140 , 156 , 280 , 269 , 171 , 261 , 237]

# Create a numpy array from weight_pound: np_weight_pound
np_weight_pound = np.array(weight_pound)

# Create an array from np_weight_pound, based on kg
np_weight_kg = np_weight_pound*0.45
np_weight_kg

array([ 67.5 , 123.75,  76.05, 106.2 ,  63.  ,  70.2 , 126.  , 121.05,
        76.95, 117.45, 106.65])

In [16]:
# calcuting players bmi
bmi = np_weight_kg / (np_height_m**2)
bmi

array([20.83333333, 26.77122769, 17.24489796, 24.08163265, 17.82480761,
       22.66270661, 28.84549346, 30.2625    , 17.44897959, 32.87981859,
       24.18367347])

In [20]:
# Create a boolean array to show players with less bmi than 18.5
light = bmi < 18.5
light

array([False, False,  True, False,  True, False, False, False,  True,
       False, False])

In [22]:
# Now we print thoseless than 18.5
print(bmi[light])

[17.24489796 17.82480761 17.44897959]


In [23]:
# std: show how close data are to mean
#Calculate mean
mean_bmi = np.mean(bmi)
#Calculate min
min_bmi = np.min(bmi)
#Calculate max
max_bmi = np.max(bmi)
#Calculate median
median_bmi = np.median(bmi)
#Calculate std
std_bmi = np.std(bmi)

In [24]:
# Print the results
print("Min : " , min_bmi)
print("Max : " , max_bmi)
print("Mean : " , mean_bmi)
print("Median : " , median_bmi)
print("Std : " , std_bmi)

Min :  17.24489795918367
Max :  32.87981859410431
Mean :  23.912642815668143
Median :  24.081632653061224
Std :  5.113986655002092
